// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuditLog.Models
{
    public partial class AuditLog
    {
        public long EventId { get; set; }
        public DateTime InsertedDate { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public string JsonData { get; set; }
        public string EventType { get; set; }
    }
}